### PR TITLE
Add integration test for buffers without trailing newline

### PR DESCRIPTION
**Pull request by juergenhoetzel**
Refs #119.

### CODE REVIEW

**Comment by rneatherway** [comment]
Travis says:

Test check-errors-without-newline condition:
    (wrong-type-argument arrayp nil)

**Comment by juergenhoetzel** [comment]
> Travis says:
> 
> Test check-errors-without-newline condition:
> (wrong-type-argument arrayp nil)

Yes, this was kind of intentional. Hopefully it will go away when i rebase on current master (which includes the fix)

**Comment by juergenhoetzel** [comment]
turned as hoped for: passed after rebasing on master 😄

**Comment by rneatherway** [comment]
:-)

**Pull request merged**
