### PR TITLE
fontify the doc string

### PR DESCRIPTION
**Pull request by nosami**
screen shot 2016-04-20 at 23 55 35

### CODE REVIEW

**Comment by rneatherway** [comment]
Very nice. I realise now this should have been updated to use the `typesig` command, but that's a separate issue.

**Comment by rneatherway** [comment]
There is a compilation error:

    fsharp-doc.el:153:1:Error: the function `fsharp-mode' is not known to be defined.

I think you could fix it with the appropriate `declare-function` as it makes the dependencies cyclic.

**Comment by nosami** [comment]
Ah cool... I spent 10 minutes on the code and then 2 hours trying and failing to work out how to fix the test :)

**Comment by rneatherway** [comment]
Sorry to hear that! Feel free to ping me about such problems.

**Comment by nosami** [comment]
Should be good now.

**Comment by rneatherway** [comment]
Great!

**Pull request merged**
