### PR TITLE
Improved logging

### PR DESCRIPTION
**Pull request by juergenhoetzel**
As discussed in [Improve *fsharp-debug* logging](https://github.com/fsharp/emacs-fsharp-mode/issues/132)

- Log caller-function (when (>= fsharp-ac-debug 3))                                                                                                                                                                
- Supply format string instead of already formatted string                                                                                                                                                         
- Human readable timestamps                                                                                                                                                                                        
- Ensure newline before log message    

I hope this will make debug logs more useful

### CODE REVIEW

**Comment by rneatherway** [comment]
It looks good, but the travis tests are failing, any idea why? It's two of the integration tests.

**Comment by juergenhoetzel** [comment]
> It looks good, but the travis tests are failing, any idea why? It's two of the integration tests.

I need to investigate. The tests run fine on my Arch Linux setup. But i can reproduce it on Centos.

Tests also fail on master branch. Maybe a timing issue. I will investigate this issue. :policeman:

**Comment by juergenhoetzel** [comment]
For whatever reason `fsharp` was not installed on the Travis build environment (maybe due to the change to container based infrastructure): This is reported in *fsharp-debug*:
```json
{
  "Kind": "project",
....
    "Logs": {
      "\/home\/juergen\/emacs\/site-elisp\/fsharp-mode\/test\/Test1\/Test1.fsproj": 
"Loading default tasks for ToolsVersion: 4.0 from \/usr\/lib\/mono\/4.5\/Microsoft.Common.tasks\nLoading default tasks for ToolsVersion: 14.0 from \/usr\/lib\/mono\/xbuild\/14.0\/bin\/Microsoft.Common.tasks\nBuild started.\nProject started.\n
Target named 'ResolveReferences' not found in the project.\nProject started.\nBuild finished.\n"
    }
  }
}
```

Maybe we could provide a better User-feedback in this case.

I added the missing *fsharp* dependency 845afc6 and also removed an old *emacs-snapshot*  which is actually older than the forelast Emacs stable release 25.1.

Travis tests now pass.

**Comment by rneatherway** [comment]
Great, thanks!

**Pull request merged**
