### PR TITLE
Move to LSP (WIP)

### PR DESCRIPTION
**Pull request by juergenhoetzel**
`fsautocomplete` [protocol change to LSP](https://github.com/fsharp/FsAutoComplete/issues/410l)

TODOS:

- [x] Remove own `flycheck/company` backends
- [x] Use [Cask](https://github.com/cask/cask) instead of  non-portable `GNU  Makefile` to automate the package development cycle; development, dependencies, testing, building, packaging 
- [x] Port tests to `LSP`
- [x] Update `README.md`

### CODE REVIEW

**Comment by MiyamotoAkira** [comment]
Anything on which you need help in here?

**Comment by juergenhoetzel** [comment]
> Anything on which you need help in here?

I already have (failing) [buttercup](jorgenschaefer/emacs-buttercup) based tests on a local branch. I will try to cleanup and  push it to this  branch this weekend.

Thank you very much for yor help!

**Comment by juergenhoetzel** [comment]
This pull request is approaching completion.

@Gastove We now use [Buttercup](https://github.com/jorgenschaefer/emacs-buttercup/blob/master/docs/writing-tests.md) for BDT testing and I did a quick and dirty conversion for your tests (using `buttercups` ert-compability macros).

**Comment by juergenhoetzel** [comment]
I'll fix the CI erros in a new PR to get things moving  :thinking:.

**Pull request merged**
