### PR TITLE
Don't panic on malformed JSON (debug messages)

### LINKED ISSUE #130: Malformed JSON "non-IL or abstract method with non-zero RVA"
Completion and tool tip does not work at all and instead this error message is produced:

```
Error: F# completion process produced malformed JSON (non-IL or abstract method with non-zero RVA).
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, "Error: F# completion process produced malformed JSON (non-IL or abstract method with non-zero RVA)."
```

This happens every time when I move the cursor to any symbol in the open buffer. I am running GNU Emacs 26.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-05-16 and Mono:

```
$ mono -V
Mono JIT compiler version 5.0.0 (Stable 5.0.0.100/9667aa6 Thu May 11 14:48:10 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

### PR DESCRIPTION
**Pull request by juergenhoetzel**
Instead just log parsing errors and try to parse next line. Fixes #130.

### CODE REVIEW

**Comment by rneatherway** [comment]
Seems reasonable, thanks. I agree the F# compiler should not be outputting
this stuff to stdout. It does worry me a little that people might find
debugging hard if there is a stack trace and we throw it away though. Any
idea how we might get around that issue?

On 2 Jun 2017 7:24 a.m., "Jürgen Hötzel" <notifications@github.com> wrote:

Instead just log parsing errors and try to parse next line. Fixes #130
<https://github.com/fsharp/emacs-fsharp-mode/issues/130>.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/fsharp/emacs-fsharp-mode/pull/131
Commit Summary

   - Don't panic on malformed JSON (debug messages)

File Changes

   - *M* fsharp-mode-completion.el
   <https://github.com/fsharp/emacs-fsharp-mode/pull/131/files#diff-0> (4)

Patch Links:

   - https://github.com/fsharp/emacs-fsharp-mode/pull/131.patch
   - https://github.com/fsharp/emacs-fsharp-mode/pull/131.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fsharp/emacs-fsharp-mode/pull/131>, or mute the thread

**Comment by juergenhoetzel** [comment]
> It does worry me a little that people might find
> debugging hard if there is a stack trace and we throw it away though. Any
> idea how we might get around that issue?

I'm not sure what you mean with "throw the stack trace away".

- Currently no stack trace is shown if the the user didn't set `(setq debug-on-error t)` 
- Users can still check `*fsharp-debug*` if something doesn't work and use *edebug* to set breakpoint

**Comment by juergenhoetzel** [comment]
By the way: In *tramp* we use `tramp-debug-message` for logging. 
I automatically  logs function-name/arguments to provide useful debug-information by default whithout verbose syntax? IMO this would also help debugging issues like this? What do you think?

**Comment by rneatherway** [comment]
Sorry, I meant an F# stack trace, which happened a few times with mono bugs
or unsigned Fsharp.core.dll. You're right to say it should be in the
*fsharp-debug* buffer in any case. I will merge this and do a release when
I'm back at my computer on Monday.

The tramp-debug-message sounds useful, I wasn't aware of that.

Thanks a lot Jürgen!


On 2 Jun 2017 6:35 p.m., "Jürgen Hötzel" <notifications@github.com> wrote:

By the way: In *tramp* we use tramp-debug-message for logging.
I automatically logs function-name/arguments to provide useful
debug-information by default whithout verbose syntax? IMO this would also
help debugging issues like this? What do you think?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fsharp/emacs-fsharp-mode/pull/131#issuecomment-305823257>,
or mute the thread

**Comment by rneatherway** [comment]
Thanks for the PR, 1.9.7 including it should be live on MELPA by tomorrow.

**Pull request merged**
