### PR TITLE
Font tidy

### PR DESCRIPTION
**Pull request by Gastove**
I found a couplefew more little bugs with my font locking revamp! This fixes 'em:

[||] <- the first pipe was being locked when it oughtn't be

<| <- was not being locked at all.

### CODE REVIEW

**Comment by Gastove** [comment]
Well, so. Ran `make test` locally, which passed; forgot to run `make test-all` which very clearly doesn't. However, the failures seem to be about completion? I sure... don't think I touched completion. 

If anyone has an intuition about what the heck has gone sideways here, I'd love a Hint in the right direction. I'll get digging, see if I can figure out what's happened.

**Comment by rneatherway** [comment]
Hey don't worry about those other tests, it can't have been you that broke
it. I'll take a look.

**Comment by juergenhoetzel** [comment]
> Hey don't worry about those other tests, it can't have been you that broke
> it. I'll take a look.

According to travis output
```
Error: F# completion process produced malformed JSON (non-IL or abstract method with non-zero RVA
non-IL or abstract method with non-zero RVA
```

this is caused by [Malformed JSON "non-IL or abstract method with non-zero RVA"](https://github.com/fsharp/emacs-fsharp-mode/issues/130), fixed by [Don't panic on malformed JSON (debug messages) ](https://github.com/fsharp/emacs-fsharp-mode/pull/131)

**Comment by Gastove** [comment]
AH. Okay, cool -- I didn't have time to look at the other bug reports/errors. Thanks, @juergenhoetzel

**Comment by rneatherway** [comment]
Thanks for the PR, 1.9.7 including it should be live on MELPA by tomorrow.

**Pull request merged**
