### PR TITLE
Record type highlighting

### PR DESCRIPTION
**Pull request by rneatherway**
Ref #74

@Holtiton thanks for the good investigation. You can see here how added a new test and tried your fix, and it seems better but not quite perfect. If you install the `faceup` package, `eval-buffer` the test file and `M-x ert-run-tests-interactively` you can try it.

You'll see a difference of
```
      ((on-line 273
                ("        «k:let» «k:rec» «f:f» («v:searchPaths»: «t:SearchPath list») («v:ptr»: «t:nativeptr»«n:<searchpath_t>») =")
                ("        «k:let» «k:rec» «f:f» («v:searchPaths»: «t:SearchPath» «v:list») («v:ptr»: «t:nativeptr»«n:<searchpath_t>») =")))))
```

Which is indicating that in a case like:

```
type RecordTest7 =
    {
    something: int
    another: string
    third: int option
    }
```

The `option` in `int option` is no longer highlighted. Any thoughts on how we could tweak the regex further?

By the way, the syntax highlighting code is very old and a bit of a mess (before I was maintainer). I think it is inherited from OCaml. I would really like to redo it properly. At least this test framework could help us to keep things under control.

### CODE REVIEW

**Comment by nosami** [comment]
I made a bunch of syntax highlighting tests here https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/master/MonoDevelop.FSharp.Tests/SyntaxHighlighting.fs They could be adapted for emacs.

**Comment by Holtiton** [comment]
This should highlight the words after type annotations
```
"[^:]:\\s-*\\(\\<[A-Za-z0-9_']*[^ ;\n,)=<-]\\)\\([ ]\\w*\\)?\\(<[^>]*>\\)?"
```
So either that or if F# only has syntactic sugar for a few types we could list them separately and should not get any surprises. This might break in some cases but it seemed to work.

Also as this is a new group, a new match is also needed. Don't know how this affects the HACK part in the match. So the complete section would be:
``` 
 `("[^:]:\\s-*\\(\\<[A-Za-z0-9_']*[^ ;\n,)=<-]\\)\\([ ]\\w*\\)?\\(<[^>]*>\\)?"
    (1 font-lock-type-face)             ; type annotations
    (2 font-lock-type-face)             ; type annotations
    ;; HACK: font-lock-negation-char-face is usually the same as
    ;; 'default'. use this to prevent generic type arguments from
    ;; being rendered in variable face
    (3 font-lock-negation-char-face nil t))
```

**Comment by rneatherway** [comment]
I was a bit surprised to find that you can do this with any generic type, not just `list` and other types from OCaml:

```
type Holder<'A> =
    | Thing of 'A

let f (x: Holder<int>) = x
let g (x: int Holder) = x
```

Your suggestion doesn't work for me, it doesn't highlight the normal single word types. I'm trying:

    "[^:]:\\s-*\\(\\<[A-Za-z_'][^\n;,)=<-]*\\)\\s-*\\(<[^>]*>\\)?"

**Comment by rneatherway** [comment]
Ignore that last one, let me know what you think of the latest version of this PR.

**Comment by Holtiton** [comment]
Seems good enough. I'm happy for now with it not matching on multiple lines as that was not pretty with my theme. 

Thanks for the fix and I'll look into at least organizing the regexes soon.

**Comment by rneatherway** [comment]
Cool, that would be great! The `faceup` module is very useful for testing this, let me know if you need help with it. @nosami's tests could also be very useful.

**Pull request merged**
