### PR TITLE
WIP: Adding new requirements for appveyor installation

### PR DESCRIPTION
**Pull request by MiyamotoAkira**
Start the process of getting the new cask/buttercup system running on appveyor

### CODE REVIEW

**Comment by MiyamotoAkira** [comment]
Tests running now. Four of them fail (also in local), and still have to fix that the end of the run should be based on the output of the commands

**Comment by juergenhoetzel** [comment]
> Tests running now. Four of them fail (also in local), and still have to fix that the end of the run should be based on the output of the commands

Thanks for working on this :+1: 
I wonder why Appveyor reports succees. Do we need something like `bash` `set -o pipefail` here:
```bash
cask exec buttercup -L . -L (Join-Path (Split-Path $PSScriptRoot -parent) "test") | Out-String
```

**Comment by MiyamotoAkira** [comment]
Could be because of Out-String. Between today and tomorrow i should be able
to get that sorted (he says hopefully), and then investigate the four
failures

**Comment by juergenhoetzel** [comment]
Appveyor installation is  obsoleted by the #249 

The windows ci-job is a bad hack because of the cask-windows problems: Any support to improve it [eldev](https://github.com/doublep/eldev) is welcome :smile:

**Pull request closed without merging**
