### PR TITLE
Use flycheck. Refs #55

### PR DESCRIPTION
**Pull request by juergenhoetzel**
Based on @nosami [ideas](https://github.com/fsharp/emacs-fsharp-mode/issues/55) I revised the error-checking code, and rewrote it completely using [flycheck](http://www.flycheck.org/en/latest/).
The *Linter* is incorporated using *flychecks* *chained-checkers*  feature.

I moved the error checking code into its own source file `flycheck-fsharp.el` like most *flycheckers* are written. There is
still more work to be done for a clean separation of *completion* and *error-checking* code. 
Screencast 
flycheck-fsharp

I use `(add-hook 'flycheck-mode-hook 'flycheck-list-errors) here.

This is WIP (need to fix tests).
Please test. Any feedback is appreciated

### CODE REVIEW

**Comment by nosami** [comment]
Looks great! Exactly what I had in mind :)

I just tried it and can't seem to get it to work though out of the box. I get the following warning

```
Warning: `flycheck-fsharp--error-callback-info` not set (flycheck-fsautocomlete not enabled?)
```

**Comment by nosami** [comment]
Ah, just need to turn on `flycheck-mode`. Perhaps this could be done automatically? The other features don't require any configuration.

**Comment by nosami** [comment]
Works great apart from that though, nice work!

One small thing (doesn't bother me personally). I know that @rneatherway wanted to have linting as a configurable option. Right now with flycheck turned on, we get compilation errors (if any) and if there are no compilation errors, then we can see the lint warnings. 

Can it be configured to not show lint warnings but still use flycheck for displaying compilation errors?

**Comment by nosami** [comment]
Maybe consider adding flycheck-pos-tip to the dependencies for tooltips?

**Comment by juergenhoetzel** [comment]
> Ah, just need to turn on flycheck-mode. Perhaps this could be done automatically? The other features don't require any configuration.

Good point. Users updating from previous `fsharp-mode` will be  irritated if error reporting doesn't work anymore. [Fixed](https://github.com/fsharp/emacs-fsharp-mode/pull/88/commits/ffde77610dae04a6e7974fd8b65b2463ee476afb) 

This will also ensure that error reporting works in Tramp buffers, because Flycheck (for unknown reasons) doesn't turn on `flycheck-mode` on automatically in Tramp buffers, even if you use `(global-flycheck-mode)`.

>  One small thing (doesn't bother me personally). I know that @rneatherway wanted to have linting as a configurable option. 
Can it be configured to not show lint warnings but still use flycheck for displaying compilation errors? (by the end user)

Can be done for current buffer:
`
(flycheck-disable-checker 'fsharp-fsautocomplete-lint)`

or global by just removing the chained checker:
`
(setq flycheck-checkers (remove  'fsharp-fsautocomplete-lint flycheck-checkers))`

>Maybe consider adding flycheck-pos-tip to the dependencies for tooltips?

My personal view is that typically Emacs users prefer to configure/customize additional packages itself. Maybe there are alternatives to `flycheck-pos-tip` ?

**Comment by nosami** [comment]
I don't think that there are any alternatives to `flycheck-pos-tip` although I could be wrong. I had it installed already.

On master, the error message is displayed whenever the point is over an error location

screen shot 2016-06-29 at 10 06 39

With this branch, if I don't have `flycheck-pos-tip` installed then I have to use the mouse to see the error displayed in the minibuffer. The flycheck error list mitigates this to a certain extent though.

**Comment by juergenhoetzel** [comment]
> On master, the error message is displayed whenever the point is over an error location

The error message is also displayed if you don't use `flycheck-pos-tip`. The default function `flycheck-display-error-messages` displays it in the minibuffer. Or did I have misunderstood you?

**Comment by juergenhoetzel** [comment]
> This is WIP (need to fix tests).

I still struggle with adapting the tests, because I have to mock a lot of flycheck internals.

@rneatherway Any options about rewriting the error tests using the 
[flycheck-ert ](https://github.com/flycheck/flycheck/blob/master/flycheck-ert.el) utility functions?

BTW: IMHO Using [Cask](https://github.com/cask/cask) would also be useful, so we can get rid of test/maintenance code?

**Comment by nosami** [comment]
>    The error message is also displayed if you don't use flycheck-pos-tip. The default function flycheck-display-error-messages displays it in the minibuffer. Or did I have misunderstood you?

It does show the error in the minibuffer, but _only_ if I click on the error with the mouse. This might be some spacemacs configuration though, not sure.

**Comment by rneatherway** [comment]
Hi guys, sorry for being a bit quiet on this one, I think it is a great idea. I definitely also support using Cask -- I tried it myself a while back but didn't finish. I will give this PR a go.

**Comment by rneatherway** [comment]
I'm happy to report that it works well for me here. The error messages show up in the minibuffer as long as the cursor is on them, and `M-n`, `M-p` take me the next and previous errors.

The flycheck-ert functions do look like a good option. If you don't have time then we should at the very least remove these tests.

**Comment by juergenhoetzel** [comment]
Finally all tests pass again :sleepy: 

I only had to  [remove the automode tests](https://github.com/fsharp/emacs-fsharp-mode/pull/88/commits/c092cbf362c0d0939c365f2567f68b29486bb1c9). There was some obscure interaction with flycheck/fsautocomplete going on which caused error conditions.
@rneatherway  IMHO these tests are kind of trivial. I hope you are fine with the removal :laughing:

**Comment by rneatherway** [comment]
Happy to merge, any last thoughts @nosami ?

Good point about the release, it has been a little while oops! I will do one tomorrow.

**Comment by nosami** [comment]
I'm happy with it, great job @juergenhoetzel !

**Comment by rneatherway** [comment]
It's awesome to see you guys pushing this forwards, great stuff!

**Comment by rneatherway** [comment]
Unfortunately after merging this there are a few test failures: https://travis-ci.org/fsharp/emacs-fsharp-mode/jobs/142984080

@juergenhoetzel would you mind taking a look, hopefully just a small semantic merge conflict.

**Comment by juergenhoetzel** [comment]
Just after/while you merged my branch a new *flycheck* release was pushed to *melpa-unstable* which [broke all generic checkers](https://github.com/flycheck/flycheck/issues/1005). I hope a new release will be made soon.

**Comment by juergenhoetzel** [comment]
@rneatherway  The new [flycheck-release](http://melpa.org/#/flycheck) fixed this issues. Tests also pass again. I hope they also add a regression test for generic checkers to avioid these kind of issues.

**Comment by rneatherway** [comment]
Thanks! I've pushed the release to rneatherway/emacs-fsharp-mode-bin, so MELPA should pick it up in a few hours. Quite a few fixes and improvements this time! [CHANGELOG](https://github.com/fsharp/emacs-fsharp-mode/blob/master/CHANGELOG.md)

**Pull request merged**
